# Generated by Django 4.2.20 on 2025-04-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='№ Рахунку'),
        ),
        migrations.AddField(
            model_name='document',
            name='asset',
            field=models.IntegerField(blank=True, null=True, verbose_name='Актив'),
        ),
        migrations.AlterField(
            model_name='document',
            name='date',
            field=models.DateField(verbose_name='Дата проводки'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('queue', 'На розпізнаванні'), ('in_progress', 'Готово до обробки'), ('completed', 'Опрацьовані'), ('error', 'Помилка'), ('unblocked', 'Деблоковано'), ('recognizing', 'Розпізнається')], default='queue', max_length=20, verbose_name='Статус'),
        ),
    ]
